package engine.game.tiles;

import engine.game.physics.Collision;
import engine.game.physics.CollisionResult;
import engine.game.physics.Hitbox.CollisionNode;
import engine.game.physics.PostProcessCollision;

/**
 * Right Ceiling Slope.
 *
 * <pre>
 *  #####
 *    ###
 *      #
 * </pre>
 */
public class RightCeilingSlope extends Slope {

    public RightCeilingSlope(int id) {
        super(id);
    }

    @Override
    protected boolean isCollisionValid_Y(
            CollisionResult result,
            PostProcessCollision slopeCollision,
            Collision collision) {

        // Allow y-collisions generated by other Slope tiles
        if (collision.tile instanceof Slope) {
            return true;
        }

        // Allow y-collisions with the ceiling at the top of the Slope
        // e.g. when the slope node has left the slope,
        // and a corner of the Hitbox has hit the ceiling
        if (getSlopeNodeX(result) < slopeCollision.getTileLeft()
                && collision.node.x < result.hitbox.width / 2) {
            return true;
        }

        // Allow y-collisions with the ceiling at the bottom of the Slope
        // e.g. when the slope node has left the slope,
        // and a corner of the Hitbox is intersecting the ceiling
        if (getSlopeNodeX(result) > slopeCollision.getTileRight()
                && collision.node.x > result.hitbox.width / 2) {
            return true;
        }

        // Disable other y-collisions while on the Slope
        return false;
    }

    @Override
    protected boolean shouldBeOnSlope(
            CollisionResult result, PostProcessCollision collision) {

        if (result.hasCollisionOccurredX()
                && getSlopeNodeX(result) < collision.getTileLeft()) {
            // The Hitbox has collided with a wall
            // (for example, if this Slope leads up to a vertical wall, and the
            //  Hitbox collided with the solid tile above the slope)
            return false;
        }

        return super.shouldBeOnSlope(result, collision);
    }

    @Override
    protected float calculateNodeYAfterCollision(
            CollisionResult result, CollisionNode node, float collisionY) {
        return collisionY + node.y;
    }

    @Override
    protected float getSlopeNodeY(CollisionResult result) {
        return result.top();
    }

    @Override
    protected boolean isPointInsideSolidArea(float x, float y) {
        return x >= y;
    }

    @Override
    protected boolean isPointInsideSummit(float xInSlope, float yInSlope) {
        return xInSlope > Tile.WIDTH && yInSlope < Tile.HEIGHT;
    }

    @Override
    protected float calculateY(float distIntoTileX) {
        /*
         *     A _____
         *       \.   |
         *         \. |
         *           \|
         *            '
         *            B
         *
         * (A) x = 0, y = 0
         * (B) x = 1, y = 1
         */
        return distIntoTileX;
    }

    @Override
    protected float getBounceMultiplierX() {
        return 1;
    }

    @Override
    protected float getBounceMultiplierY() {
        return 1;
    }

}
